name: mhr_buddy
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_floating_bottom_bar: ^1.0.0+1
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.0.0
  lazy_load_scrollview: ^1.3.0
  simple_shadow: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/jsons/
    - assets/images/
    - assets/images/app_logo/
    - assets/images/monsters/
    - assets/images/items/
    - assets/images/weapons/
    - assets/images/weapons/bow_guns/
    - assets/images/weapons/bows/
    - assets/images/weapons/charge_blades/
    - assets/images/weapons/duel_blades/
    - assets/images/weapons/great_swords/
    - assets/images/weapons/gunlances/
    - assets/images/weapons/hammers/
    - assets/images/weapons/insect_glaives/
    - assets/images/weapons/lances/
    - assets/images/weapons/long_swords/
    - assets/images/weapons/sword_&_shields/
